Month 12/step 1
AlexeyNewDeveloper/algososh pull request #2
Opened 2023-04-05 22:10 UTC by AlexeyNewDeveloper

2023-04-06 04:25 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Была проделана огромная работа 🔥.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализованы все алгоритмы.

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx, он вам не понадобится;

- "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE;

- По чек-листу: функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, вынесены в отдельные файлы utils.ts в папке соответствующего компонента;

- Связный список:

  - При добавлении/удалению по индексу, вы должны проверять, "существует" ли такой индекс вообще. <https://disk.yandex.com/i/jeaOA6edS_DOdw>

### **Сделает код лучше:**

- Посмотрите ещё раз работу анимации алгоритмов сортировки, она у вас немного затормаживает. Это происходит когда массив уже построен в правильной последовательности, но работа сортировки не завершена (ну или так и задумано);

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  }
**Надо исправить:**

функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, вынесены в отдельные файлы utils.ts в папке соответствующего компонента;

Вообщем, нужно просто вынести функцию в `components/fibonacci-page/utils.ts`

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    number: null,
**Можно лучше:**

если вы точно знаете, что в `number` будет строка, то тут лучше использовать `""`, а не `null`, чтобы js лишний раз не менял тип. 

А не проще сразу сделать тип `number`?, просто не вижу веских причин тут делать тип `string`.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +            }}
**Можно лучше:**

Обработчик событий лучше вынести в отдельную функцию.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +            max={19}
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE. Желательно вынести в файл `utils`, только не в общий, а который принадлежит компоненту;

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +              Number(values.number) > 19
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE. Желательно вынести в файл `utils`

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +      }, 500);
**Надо испраивить:**

у вас есть константы `src/constants/delay.ts`, используйте их.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +          }, 1000);
**Надо испраивить:**

у вас есть константы `src/constants/delay.ts`, используйте их.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/string/string.tsx
> +    delayNumber: number = 1000
**Надо испраивить:**

у вас есть константы `src/constants/delay.ts`, используйте их.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +    delay: number = 500
**Надо испраивить:**

у вас есть константы `src/constants/delay.ts`, используйте их.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +              }, 500);
**Надо испраивить:**

у вас есть константы `src/constants/delay.ts`, используйте их.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +            }, 500);
**Надо испраивить:**

у вас есть константы `src/constants/delay.ts`, используйте их.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +    delay: number = 500
**Надо испраивить:**

у вас есть константы `src/constants/delay.ts`, используйте их.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +              selectionSort(array, "asc", 500);
**Надо испраивить:**

Здесь и далее.

у вас есть константы `src/constants/delay.ts`, используйте их.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +    delay: number = 500
**Надо испраивить:**

у вас есть константы `src/constants/delay.ts`, используйте их.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +    changingElementIndex: number
**Можно лучше:**

Параметр не используется, думаю лучше его удалить.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +    changingValue: IItemObject,
**Можно лучше:**

Параметр не используется, думаю лучше его удалить.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +    const isNotHeadOrTail: boolean =
**Можно лучше:**

тут можно не указывать явно тип, т.к. ts сам подхватит.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +            maxLength={4}
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +                          : ""
**Можно лучше:**

Большие выражения в `jsx` лучше выносить в отдельную переменную.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +            maxLength={4}
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +            maxLength={4}
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2023-04-06 04:25 UTC, ArslanDev666 commented on src/components/string/string.tsx
> +            maxLength={11}
**Надо исправить:**

"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2023-04-06 06:26 UTC, AlexeyNewDeveloper commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    number: null,
Мне в любом случае нужно где то делать изменение типа. Потому что в Инпут поступает 100% строка(в e.currentTarget.value). Если я укажу тип number в 19 строке, то мне нужно будет приводить строку в число в общей ф-и handleChange - а для этого нужно конкретно ее изменить, ведь useForm используется и в других компонентах.
Если ставить вместо null пустую строку, то js потом мне сконвертирует ее в 0. Поэтому, мне кажется нет разницы, если js поменяет null на 0, либо "" на 0.
Поэтому, поскольку конвертация из строки в число неизбежна, то я лучше явно буду это делать в ф-и showItems

2023-04-07 05:47 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    number: null,
Не забывайте, что у вас есть `setValues` из того же `useForm`, вам никто не мешает, через него делать обработчик событий, и там выполнить преобразование.  

```js
const { values, setValues } = useForm<{ number: number }>({ number: 0 });

const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
  const value = e.target.value;

  setValues({ number: +value });
};

// ...

<Input
  name='number'
  onChange={handleChange}
  max={MAX_NUMBER}
  isLimitText={true}
  type='number'
  extraClass='mr-12'
  value={values.number || ''}
/>
<Button
  isLoader={loading}
  disabled={values.number > MAX_NUMBER}
  onClick={onClickButton}
  text='Рассчитать'
/>
```

Это намного лучше, чем делать несколько раз из строки - число.

По поводу `null` и "" - тут уже идёт микро-оптимизация)) так что разница всё же есть, ну и null обычно используется для обозначения отсутствия значения, когда неизвестно, какой тип данных будет использоваться или значение переменной может быть любого типа данных.

2023-04-07 05:49 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! 🔥 Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-04-28 09:46 UTC, merged